#
# What : Playbook to :
#		- Initialize Working Dir
#		- Connect to Github
#		- Save local code to branch
#		- Tag the Branch and delte the Branch (Tag is kept in GIT)
#
# Date : 21.June 2018 Walter Brunelli
#
# Usage: ansible-playbook pl_dsf_git_workflow_clean_repo.yml
#	 ansible-playbook pl_dsf_git_workflow_clean_repo.yml -e "repo_url=https://github.com/wbrunell/repo01"
#	 ansible-playbook pl_dsf_git_workflow_clean_repo.yml -e "repo_dir_name=repo01"
#	 ansible-playbook pl_dsf_git_workflow_clean_repo.yml -e "local_base_dir=/var/tmp"

---
- name: Save current status in a branch
  hosts: localhost
  become_user: none
  become: no
  vars_files:
    - pl_dsf_git_workflow_all_setupvariables.yml
  vars:
    backup_branch_name: backup_{{ansible_date_time.date}}_{{ansible_date_time.hour}}-{{ansible_date_time.minute}}-{{ansible_date_time.second}}
    backup_tag_name: 	backup_dwproot_{{ansible_date_time.date}}_{{ansible_date_time.hour}}-{{ansible_date_time.minute}}-{{ansible_date_time.second}}
    temp_repo_dir_name: "{{repo_dir_name}}_temp"

  tasks:
    - name: Check that the  Directory exists
      stat: path={{local_base_dir}}/{{repo_dir_name}}
      register: dir
    - debug: msg="Exiting Directory does not exist"
      when: dir.stat.isdir == false
    - name: End Play 
      meta: end_play
      when: dir.stat.isdir == false

    - name: Check that the Directory is not already under GIT control
      stat: path={{local_base_dir}}/{{repo_dir_name}}/.git
      register: dir
    - debug: msg="Exiting, Directory is already under GIT control"
      when: dir.stat.exists == true
    - name: End Play 
      meta: end_play
      when: dir.stat.exists == true

    - name: Delete temporary dir if it exists
      file: path={{local_base_dir}}/{{temp_repo_dir_name}} state=absent

    - name: Clone Repo to temporary location
      shell: 'cd /var/tmp; git clone {{repo_url}} {{temp_repo_dir_name}}'

    - name: Copy GIT config from temp_repo to my repo and add/commit all files and tag the new version
      shell: "{{item}}"
      with_items:
        - 'cd {{local_base_dir}}/{{repo_dir_name}}; git init .'
        - 'cd {{local_base_dir}}/{{repo_dir_name}}; cp -pr ../{{temp_repo_dir_name}}/.git .'
        - 'cd {{local_base_dir}}/{{repo_dir_name}}; git add .'
        - 'cd {{local_base_dir}}/{{repo_dir_name}}; git commit -m "Overwriting the master branch with code from /dwp_root"'
        - 'cd {{local_base_dir}}/{{repo_dir_name}}; git tag NEW-TAG -m "This is the code from dwp_root in"' 
        - 'cd {{local_base_dir}}/{{repo_dir_name}}; git push origin master --tags'
#        - 'cd {{local_base_dir}}/{{repo_dir_name}}; git diff master {{backup_tag_name}}'

    - name: Delete temporary dir 
      file: path={{local_base_dir}}/{{temp_repo_dir_name}} state=absent

