#
# What : Playbook to instal a specific RPM on all DSF TEST server 
#        Environment : 	DEV	TML-Repo
#	  		TEST	TML-Repo
#			PROD	DML-Repo
#
# Date : 01.March 2018 Walter Brunelli
#

---
- name: Install on TEST server
  hosts: dsf_test
  become_user: root
  become: yes
  vars:
    stream_feed: "{{ stream_feed_name | default('dsf-pseudo-xxx') }}"
  tasks:
    - name: Make yum cache expire in order to re-read updated reposerver metadata
      shell: yum clean expire-cache warn=no
    - name: Update repo metadata
      shell: yum repolist warn=no
    - name: Install package
      # yum: name={{stream_feed}}-{{hostvars.cos019.latest_tag.stdout[1:]}}-0.noarch state=present
      yum: name={{stream_feed}} state=latest
