#
# What : Playbook to add and commit changes to GIT with file-selection option
#	 This includes :	- remove all files
#				- remove all tags
#				- remove all branches
#				- create new empty files t1 t2 t3 t4
#
# Date : 17.May 2018 Walter Brunelli
#
# Usage: ansible-playbook ${0}.yml
#	 ansible-playbook ${0}.yml -e "repo_url=https://github.com/wbrunell/repo01"
#	 ansible-playbook ${0}.yml -e "repo_dir_name=repo01"
#	 ansible-playbook ${0}.yml -e "local_base_dir=/var/tmp"
#	 ansible-playbook ${0}.yml -e "release_change_type: {major|minor|patch}"
#	 ansible-playbook ${0}.yml -e "file_selection=<file1 file2 ..>"		# Default is: . (all changes)

---
- name: Clean the repo-directory
  hosts: localhost
  become_user: none
  become: no
  vars_files:
    - pl_dsf_git_workflow_all_setupvariables.yml
  # Prompt the user what kind of release change it is (major|mionor|patch)
  vars_prompt:
    - name: release_change_type_id
      prompt: "What kind of change are you about to release ? \nRequired to identify which field of the version number will be increased. \n1- major\n2- minor\n3- patch"
  tasks:
  ## Do some checks
    - name: Check if Directory exists
      stat: path={{local_base_dir}}/{{repo_dir_name}}/.git
      register: dir
    - name: Exit if directory does not exists
      fail: msg="Local directory {{local_base_dir}}/{{repo_dir_name}} does not exist. Exiting."  
      when: dir.stat.exists == false

    - name: Check if there are changes to add and commit
      # shell: 'cd {{local_base_dir}}/{{repo_dir_name}}; /usr/local/bin/git diff --exit-code >/dev/null 2>&1'
      shell: 'cd {{local_base_dir}}/{{repo_dir_name}}; /usr/local/bin/git ls-files --other -m --exclude-standard | wc -l | grep 0 >/dev/null 2>&1'
      failed_when: false
      ignore_errors: true
      register: result
    - debug: msg="Exiting Playbook. There are no changes in the working directory. Status is clean"
      when: result.rc == 0
    - name: End Play if there are no changes in the Working-Dir
      meta: end_play
      when: result.rc == 0

    - name: Check that the selected file(s) exists and has/have been updated or is/are new to Git (untracked)
      shell: 'cd {{local_base_dir}}/{{repo_dir_name}}; git ls-files --other -m --exclude-standard --error-unmatch {{file_selection}} >/dev/null 2>&1'
      failed_when: false
      ignore_errors: true
      register: result
    - debug: msg="Exiting Playbook. The given file(s) {{file_selection}} does/do not exist or is not being modified"
      when: result.rc != 0
    - name: End Play if there are no changes in the Working-Dir
      meta: end_play
      when: result.rc != 0

#    - name: Check if you have read and write access to the Github-Repo : To be finished !
#      shell: 'cd {{local_base_dir}}/{{repo_dir_name}}; git push origin master >/dev/null 2>&1'
#      failed_when: false
#      ignore_errors: true
#      register: result
    
    ## Do the real work
    - name: Add and commit changes 
      shell: 'cd {{local_base_dir}}/{{repo_dir_name}}; git add {{file_selection}} ; {{commit_command}}'

    - name: Find latest version (tag)
      shell: 'cd {{local_base_dir}}/{{repo_dir_name}}; git tag --sort=creatordate | tail -1'
      register: latest_tag  

    - name: Print latest tag
      debug: var=latest_tag.stdout

    - name: Set new Git tag - major number increase 
#      shell: 'cd {{local_base_dir}}/{{repo_dir_name}}; /usr/local/bin/git tag {{item}} -m "{{item}}" -m "{{tag_comment}}"'
      shell: 'cd {{local_base_dir}}/{{repo_dir_name}}; {{tag_command}}'
      with_items:
        - "{{latest_tag.stdout.split('.')[0] | int + 1}}.0.0"
      when: release_change_type_id == "1"

    - name: Set new Git tag - minor number increase
#      shell: 'cd {{local_base_dir}}/{{repo_dir_name}}; /usr/local/bin/git tag {{item}} -m "{{item}}" -m "{{tag_comment}}"'
      shell: 'cd {{local_base_dir}}/{{repo_dir_name}}; {{tag_command}}'
      with_items:
        - "{{latest_tag.stdout.split('.')[0]}}.{{latest_tag.stdout.split('.')[1] | int + 1}}.0"
      when: release_change_type_id == "2"

    - name: Set new Git tag - patch number increase
#      shell: 'cd {{local_base_dir}}/{{repo_dir_name}}; /usr/local/bin/git tag {{item}} -m "{{item}}" -m "{{tag_comment}}"'
      shell: 'cd {{local_base_dir}}/{{repo_dir_name}}; {{tag_command}}'
      with_items:
        - "{{latest_tag.stdout.split('.')[0]}}.{{latest_tag.stdout.split('.')[1]}}.{{latest_tag.stdout.split('.')[2] | int + 1}}"
      when: release_change_type_id == "3"

    - name: Push commits and tag to Github
      shell: 'cd {{local_base_dir}}/{{repo_dir_name}}; /usr/local/bin/git push origin master --tags'

    - name: Find new version (tag)
      shell: 'cd {{local_base_dir}}/{{repo_dir_name}}; git tag --sort=creatordate | tail -1' 
      register: new_tag  

    - name: Show difference between new and old version
      shell: 'cd {{local_base_dir}}/{{repo_dir_name}}; /usr/local/bin/git diff {{new_tag.stdout}} {{latest_tag.stdout}}'
